import Head from 'next/head'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet">
      </Head>

      <main className="">
        <h1>Hello</h1>
      </main>

      <footer className="">

      </footer>
    </div>
  )
}
