import Head from 'next/head'
import mainpage from './mainpage'


export default function Home() {
  return (
    <div className="bg-[#292929] w-full h-screen">
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet" />
      </Head>

      <main>
        <mainpage />
      </main>

      <footer className="">

      </footer>
    </div>
  )
}
